<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../Environment.props" />
  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <AssemblyName>RuneExtractionValidation</AssemblyName>
    <LangVersion>10</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="EpicLoot">
      <HintPath>$(BEPINEX_PLUGINS)/RandyKnapp-EpicLoot/EpicLoot.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
